TMDT/Controllers/AdminCaiDatController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TMDT.Models;

namespace TMDT.Controllers
{
    public class AdminCaiDatController : Controller
    {
        private TMDTDBDataContext data = new TMDTDBDataContext();

        // GET: AdminCaiDat
        public ActionResult Index(bool? result)
        {
            if (!Manager.LoggedAsAdmin())
            {
                return RedirectToAction("Login", "Admin");
            }

            List<CaiDat> configs = data.CaiDats.ToList();
            if (result != null)
            {
                ViewBag.Result = (bool)result ? "Cập nhật thành công." : null;
            }
            return View(configs);
        }

        [HttpPost]
        public ActionResult ApplyConfig(FormCollection form, HttpPostedFileBase[] fileUpload)
        {
            List<CaiDat> configs = data.CaiDats.ToList();
            string validateMsg = string.Empty;

            foreach (CaiDat cf in configs)
            {
                switch (cf.TenThamSo)
                {
                    case "top_san_pham_take":
                        string input = form["top_san_pham_take"];
                        if (string.IsNullOrWhiteSpace(input) || !IsDigit(input))
                        {
                            ViewData["Error" + cf.TenThamSo] = "Giá trị không hợp lệ";
                            return View("Index", configs);
                        }
                        else
                        {
                            int iinput = Convert.ToInt32(input);
                            if (iinput < 1 || iinput > 10)
                            {
                                ViewData["Error" + cf.TenThamSo] = "Hãy nhập giá trị trong khoảng từ 1-10";
                                return View("Index", configs);
                            }
                        }
                        break;
                    case "top_tai_khoan_take":
                        input = form["top_tai_khoan_take"];
                        if (string.IsNullOrWhiteSpace(input) || !IsDigit(input))
                        {
                            ViewData["Error" + cf.TenThamSo] = "Giá trị không hợp lệ";
                            return View("Index", configs);
                        }
                        else
                        {
                            int iinput = Convert.ToInt32(input);
                            if (iinput < 1 || iinput > 10)
                            {
                                ViewData["Error" + cf.TenThamSo] = "Hãy nhập giá trị trong khoảng từ 1-10";
                                return View("Index", configs);
                            }
                        }
                        break;
                    case "hinh_logo":
                        if (fileUpload[0] != null)
                        {
                            string name = Path.GetFileName(fileUpload[0].FileName);
                            string ServerSavePath = Path.Combine(Server.MapPath("~/Images/LogoBanner/") + name);

                            if (!System.IO.File.Exists(ServerSavePath))
                            {
                                fileUpload[0].SaveAs(ServerSavePath);
                            }
                            form[cf.TenThamSo] = name;
                        }
                        else
                        {
                            continue;
                        }
                        break;
                    case "hinh_banner_1":
                        if (fileUpload[1] != null)
                        {
                            string name = Path.GetFileName(fileUpload[1].FileName);
                            string ServerSavePath = Path.Combine(Server.MapPath("~/Images/LogoBanner/") + name);

                            if (!System.IO.File.Exists(ServerSavePath))
                            {
                                fileUpload[1].SaveAs(ServerSavePath);
                            }
                            form[cf.TenThamSo] = name;
                        }
                        else
                        {
                            continue;
                        }
                        break;
                    case "hinh_banner_2":
                        if (fileUpload[2] != null)
                        {
                            string name = Path.GetFileName(fileUpload[2].FileName);
                            string ServerSavePath = Path.Combine(Server.MapPath("~/Images/LogoBanner/") + name);

                            if (!System.IO.File.Exists(ServerSavePath))
                            {
                                fileUpload[2].SaveAs(ServerSavePath);
                            }
                            form[cf.TenThamSo] = name;
                        }
                        else
                        {
                            continue;
                        }
                        break;
                    case "hinh_banner_3":
                        if (fileUpload[3] != null)
                        {
                            string name = Path.GetFileName(fileUpload[3].FileName);
                            string ServerSavePath = Path.Combine(Server.MapPath("~/Images/LogoBanner/") + name);

                            if (!System.IO.File.Exists(ServerSavePath))
                            {
                                fileUpload[3].SaveAs(ServerSavePath);
                            }
                            form[cf.TenThamSo] = name;
                        }
                        else
                        {
                            continue;
                        }
                        break;
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        string tenThamSo = cf.TenThamSo;
                        string giaTri = form[cf.TenThamSo];

                        data.p_UpdateCaiDat(tenThamSo, giaTri);
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Error = ex.ToString();
                        View("Index", configs);
                    }
                }
            }

            return RedirectToAction("Index", new { result = true });
        }

        private bool IsDigit(string input)
        {
            foreach (char c in input)
            {
                if (!char.IsDigit(c))
                {
                    return false;
                }
            }
            return true;
        }








        [ChildActionOnly]
        public ActionResult PV_Header()
        {
            CaiDat logo = data.CaiDats.SingleOrDefault(i => i.TenThamSo.Equals("hinh_logo"));
            ViewBag.UrlLogo = Url.Content("~/Images/LogoBanner/" + logo.GiaTri);

            string[] banners = { "hinh_banner_1", "hinh_banner_2", "hinh_banner_3" };
            foreach (string sbanner in banners)
            {
                CaiDat banner = data.CaiDats.SingleOrDefault(i => i.TenThamSo.Equals(sbanner));
                ViewData["Url_" + sbanner] = Url.Content("~/Images/LogoBanner/" + banner.GiaTri);
            }

            return PartialView();
        }

    }
}

TMDT/Controllers/AdminThongKeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TMDT.Models;
using PagedList;

namespace TMDT.Controllers
{
    public class AdminThongKeController : Controller
    {
        private TMDTDBDataContext data = new TMDTDBDataContext();

        public ActionResult Index()
        {
            if (!Manager.LoggedAsAdmin())
            {
                return RedirectToAction("Login", "Admin");
            }

            return View();
        }

        #region SanPham
        public ActionResult SanPham(int? page)
        {
            if (!Manager.LoggedAsAdmin())
            {
                return RedirectToAction("Login", "Admin");
            }

            List<MonthYear> distinct = data.V_ThongKeSanPhams.Select(i => new MonthYear((int)i.Thang, (int)i.Nam)).Distinct().ToList();
            distinct.Reverse();

            int pageSize = 12;
            int pageNum = page ?? 1;
            return View(distinct.ToPagedList(pageNum, pageSize));
        }

        [ChildActionOnly]
        //Dùng trong Index
        public ActionResult PV_ThongKeSanPham()
        {
            int month = DateTime.Now.Month;
            int year = DateTime.Now.Year;

            ViewBag.Month = month;
            ViewBag.Year = year;

            CaiDat config = data.CaiDats.SingleOrDefault(i => i.TenThamSo.Equals("top_san_pham_take"));
            int take = Convert.ToInt32(config.GiaTri);
            ViewBag.Take = take;

            List<V_ThongKeSanPham> all = data.V_ThongKeSanPhams.Where(i => i.Thang == month && i.Nam == year).OrderByDescending(i => i.TongSoLuong).Take(take).ToList();

            string list_labels = "[";
            foreach (V_ThongKeSanPham item in all)
            {
                if (all.IndexOf(item) == all.Count - 1)
                {
                    list_labels += "'" + item.TenSanPham + "'";
                }
                else
                {
                    list_labels += "'" + item.TenSanPham + "'" + ",";
                }
            }
            list_labels += "]";
            ViewBag.List_labels = list_labels;

            string list_data = "[";
            foreach (V_ThongKeSanPham item in all)
            {
                if (all.IndexOf(item) == all.Count - 1)
                {
                    list_data += "" + item.TongSoLuong + "";
                }
                else
                {
                    list_data += "" + item.TongSoLuong + "" + ",";
                }
            }
            list_data += "]";
            ViewBag.List_data = list_data;

            return PartialView(all);
        }

        [ChildActionOnly]
        //Dùng trong SanPham
        public ActionResult PV_SanPhamByMonthYear(int month, int year)
        {
            List<V_ThongKeSanPham> all = data.V_ThongKeSanPhams.Where(i => i.Thang == month && i.Nam == year).OrderByDescending(i => i.TongSoLuong).ToList();
            return PartialView(all);
        }
        #endregion
        #region User
        public ActionResult TaiKhoan(int? page)
        {
            if (!Manager.LoggedAsAdmin())
            {
                return RedirectToAction("Login", "Admin");
            }

            List<MonthYear> distinct = data.V_ThongKeUsers.Select(i => new MonthYear((int)i.Thang, (int)i.Nam)).Distinct().ToList();
            distinct.Reverse();

            int pageSize = 12;
            int pageNum = page ?? 1;
            return View(distinct.ToPagedList(pageNum, pageSize));
        }


        [ChildActionOnly]
        //Dùng trong Index
        public ActionResult PV_ThongKeUser()
        {
            int month = DateTime.Now.Month;
            int year = DateTime.Now.Year;

            ViewBag.Month = month;
            ViewBag.Year = year;

            CaiDat config = data.CaiDats.SingleOrDefault(i => i.TenThamSo.Equals("top_tai_khoan_take"));
            int take = Convert.ToInt32(config.GiaTri);
            ViewBag.Take = take;

            List<V_ThongKeUser> all = data.V_ThongKeUsers.Where(i => i.Thang == month && i.Nam == year).OrderByDescending(i => i.TongThanhTien).Take(take).ToList();

            string list_labels = "[";
            foreach (V_ThongKeUser item in all)
            {
                if (all.IndexOf(item) == all.Count - 1)
                {
                    list_labels += "'" + item.Username + "'";
                }
                else
                {
                    list_labels += "'" + item.Username + "'" + ",";
                }
            }
            list_labels += "]";
            ViewBag.List_labels = list_labels;

            string list_data_TongThanhTien = "[";
            foreach (V_ThongKeUser item in all)
            {
                if (all.IndexOf(item) == all.Count - 1)
                {
                    list_data_TongThanhTien += "" + item.TongThanhTien + "";
                }
                else
                {
                    list_data_TongThanhTien += "" + item.TongThanhTien + "" + ",";
                }
            }
            list_data_TongThanhTien += "]";
            ViewBag.List_data_TongThanhTien = list_data_TongThanhTien;

            return PartialView(all);
        }

        [ChildActionOnly]
        //Dùng trong TaiKhoan
        public ActionResult PV_TaiKhoanByMonthYear(int month, int year)
        {
            List<V_ThongKeUser> all = data.V_ThongKeUsers.Where(i => i.Thang == month && i.Nam == year).OrderByDescending(i => i.TongThanhTien).ToList();
            return PartialView(all);
        }

        #endregion
        #region DoanhThu
        public ActionResult DoanhThu(int? page)
        {
            if (!Manager.LoggedAsAdmin())
            {
                return RedirectToAction("Login", "Admin");
            }

            List<V_ThongKeDoanhThu> distinct = data.V_ThongKeDoanhThus.ToList();
            distinct.Reverse();

            int pageSize = 12;
            int pageNum = page ?? 1;
            return View(distinct.ToPagedList(pageNum, pageSize));
        }

        [ChildActionOnly]
        //Dùng trong Index
        public ActionResult PV_ThongKeDoanhThu()
        {
            int takeMonth = 12;

            List<V_ThongKeDoanhThu> all = data.V_ThongKeDoanhThus.OrderByDescending(i => i.Nam).OrderByDescending(i => i.Thang).Take(takeMonth).ToList();
            all.Reverse();

            string textMonth = "Tháng";
            int year = 0;
            string list_labels = "[";
            foreach (V_ThongKeDoanhThu item in all)
            {
                if (item.Nam != year)
                {
                    year = (int)item.Nam;
                    list_labels += string.Format("['{0} {1}', '{2}']", textMonth, item.Thang, year);
                }
                else
                {
                    list_labels += "'" + item.Thang + "'";
                }

                if (all.IndexOf(item) != all.Count - 1)
                {
                    list_labels += ",";
                }
            }
            list_labels += "]";
            ViewBag.List_labels = list_labels;

            string list_data = "[";
            foreach (V_ThongKeDoanhThu item in all)
            {
                if (all.IndexOf(item) == all.Count - 1)
                {
                    list_data += "" + item.TongDoanhThu + "";
                }
                else
                {
                    list_data += "" + item.TongDoanhThu + "" + ",";
                }
            }
            list_data += "]";
            ViewBag.List_data = list_data;

            return PartialView(all);
        }
        #endregion

    }
}

TMDT/Controllers/TimKiemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TMDT.Models;
using PagedList;
using PagedList.Mvc;

namespace TMDT.Controllers
{
    public class TimKiemController : Controller
    {
        // GET: TimKiem
        private TMDTDBDataContext data = new TMDTDBDataContext();
        [HttpPost]
        public ActionResult KetQuaTimKiem(int? page, FormCollection f)
        {
            if (string.IsNullOrWhiteSpace(f["txtTimkiem"]))
            {
                return RedirectToAction("Index", "Home");
            }
            string tukhoa = f["txtTimkiem"].ToString();
            ViewBag.TK = tukhoa;
            List<SanPham> lsKQTK = data.SanPhams.Where(n => n.TenSanPham.Contains(tukhoa)).ToList();
            int pageSize = 6;
            int pageNum = (page ?? 1);
            if (lsKQTK.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy";
                return View(data.SanPhams.OrderBy(n => n.TenSanPham).ToPagedList(pageNum, pageSize));
            }
            ViewBag.ThongBao = "Đã tìm thấy" + " " + lsKQTK.Count + " " + "kết quả";
            return View(lsKQTK.OrderBy(n => n.TenSanPham).ToPagedList(pageNum, pageSize));
        }
        [HttpGet]
        public ActionResult KetQuaTimKiem()
        {
            return RedirectToAction("Index", "KhongTen");
        }
    }
}

TMDT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - NPL</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    @Html.Action("PV_Header", "AdminCaiDat")

    <div class="clearfix"></div>
    <nav class="navbar navbar-expand-md bg-custom navbar-dark">



        <!-- Brand -->
        @Html.ActionLink("Home", "Index", "Home", null, new { @class = "navbar-brand navbar-brand-custom" })

        <!-- Toggler/collapsibe Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navbar links -->
        <div class="collapse navbar-collapse navbar-collapse-custom" id="collapsibleNavbar">
            <ul class="navbar-nav mr-auto">

                @*@Html.Action("PartialNavbarItem", "Home")*@
            </ul>
            <ul class="navbar-nav">     

                @Html.Action("TaiKhoan", "NguoiDung")

                <li class="nav-item">
                    @using (Html.BeginForm("KetQuaTimKiem", "TimKiem", FormMethod.Post, new { @class = "form-inline" }))
                    {
                        <div class="form-group">
                            <input type="text" name="txtTimkiem" class="form-control" placeholder="Search" required>
                        </div>
                        <button type="submit" class="btn btn-success">
                            Search
                        </button>
                    }
                </li>
            </ul>
        </div>
    </nav> 


    <br />

    @RenderBody()

    
    <div class="container body-content">

        <hr />
        <footer>



            <section id="footer-bar" style="background-color:tomato">
                <div class="container">
                    <div class="row">
                        <div class="col-3" style="padding-left: 25px; min-width:250px">
                            <h4>Liên hệ</h4>
                            <ul class="contact">
                                <li>
                                    Địa chỉ: 475A Điện Biên Phủ
                                </li>
                                <li>
                                    SĐT: 38456123
                                </li>
                            </ul>
                        </div>
                        @*Fanpage Facebook*@
                        <div class="col-4" style="min-width:250px">
                            <h4>Kết nối với chúng tôi</h4>
                            <div style="height:auto; width:inherit" class="fb-page icon-repeat" data-href="https://www.facebook.com/NPL-583877955305428/" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/NPL-583877955305428/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/NPL-583877955305428/">NPL</a></blockquote></div>

                        </div>
                        @*Zalo chat*@
                        <div class="zalo-chat-widget " data-oaid="2443317400706361226" data-welcome-message="Rất vui khi được hỗ trợ bạn!" data-autopopup="1" data-width="350" data-height="420"></div>
                        <script src="https://sp.zalo.me/plugins/sdk.js"></script>
                        @*Maps*@
                        <div class="col-5" style="min-width:250px">
                            <h4>Trải nghiệm trực tiếp</h4>
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.123600824663!2d106.71265711449475!3d10.801844361678471!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317528a459cb43ab%3A0x6c3d29d370b52a7e!2sHUTECH+University!5e0!3m2!1sen!2s!4v1522915287888" frameborder="1" style="border:medium; width:inherit; height:auto"></iframe>

                        </div>
                    </div>
                </div>
            </section>

            <p>&copy; @DateTime.Now.Year - Thương Mại Điện Tử</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/otherscript")
    @RenderSection("scripts", required: false)

    <div id="fb-root"></div>
    <script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = 'https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.12';
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>


</body>
</html>

TMDT/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Control Panel</title>
    @Styles.Render("~/Content/admincss")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-md bg-dark navbar-dark fixed-top">
        <!-- Brand -->
        @Html.ActionLink("Bảng điều khiển", "Index", "Admin", null, new { @class = "navbar-brand" })
        <!-- Toggler/collapsibe Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Navbar links -->
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav mr-auto">
                <!-- Dropdown -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                        Quản lý
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="@Url.Action("Index", "AdminNhom")">Nhóm</a>
                        <a class="dropdown-item" href="@Url.Action("Index", "AdminLoai")">Loại</a>
                        <a class="dropdown-item" href="@Url.Action("Index", "AdminNSX")">NSX</a>
                        <a class="dropdown-item" href="@Url.Action("Index", "AdminSanPham")">Sản phẩm</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "AdminKhuyenMai")">Khuyến mại</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "AdminThongKe")">Thống kê</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "AdminCaiDat")">Cài đặt</a>
                </li>
                <!-- Dropdown -->
                @if (Session["Account"] != null && Session["Role"].Equals("Admin"))
                {
                    <li class="nav-item">
                        <a class="nav-link dropdown-toggle btn btn-dark btn-dropdown-custom" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Admin
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="@Url.Action("ChangePassword", "Admin")">Đổi mật khẩu</a>
                            <a class="dropdown-item" href="@Url.Action("Logs", "Admin")">Lịch sử đăng nhập</a>
                            <a class="dropdown-item" href="@Url.Action("Logout", "Admin")">Đăng xuất</a>
                        </div>
                    </li>
                }
            </ul>
        </div>
    </nav>
    <div class="container" style="margin-top: 80px">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/popper")
    @Scripts.Render("~/bundles/bootstrap")
    <script>
        var path_to_delete;

        $(".deleteItem").click(function (e) {
            path_to_delete = $(this).data('path');
            $('#deleteID').attr("value", path_to_delete);
        });

        $(document).ready(function () {
            $("#errorModal").modal();

            var t = $('#dropdown_SanPham').val();

            if (t !== "") {
                $.post("@Url.Action("SanPhamById", "AdminKhuyenMai")?val=" + t, function(res) {
                    if (res.Success === "true") {

                        //enable the text boxes and set the value

                        $("#DonGia").prop("value", res.Data.DonGia);

                    } else {
                    }
                });
            } else {
            }

            var t = $('#GiamGia').val();
            var idSanPham = $('#dropdown_SanPham').val();

            if (t !== "") {
                $.post("@Url.Action("GetGiaKhuyenMai", "AdminKhuyenMai")?idSanPham=" + idSanPham + "&val=" + t, function(res) {
                    if (res.Success === "true") {

                        //enable the text boxes and set the value

                        $("#GiaKhuyenMai").prop("value", res.Data.GiaKhuyenMai);

                    } else {
                    }
                });
            } else {
            }
        });
    </script>
    <script type="text/javascript">
        $("#dropdown_SanPham").change(function() {

            var t = $(this).val();

            if (t !== "") {
                $.post("@Url.Action("SanPhamById", "AdminKhuyenMai")?val=" + t, function(res) {
                    if (res.Success === "true") {

                        //enable the text boxes and set the value

                        $("#DonGia").prop("value", res.Data.DonGia);

                    } else {
                        alert("Error getting data!");
                    }
                });
            } else {
            }

        });
        $("#GiamGia").change(function() {

            var t = $(this).val();
            var idSanPham = $('#dropdown_SanPham').val();

            if (t !== "") {
                $.post("@Url.Action("GetGiaKhuyenMai", "AdminKhuyenMai")?idSanPham=" + idSanPham + "&val=" + t, function(res) {
                    if (res.Success === "true") {

                        //enable the text boxes and set the value

                        $("#GiaKhuyenMai").prop("value", res.Data.GiaKhuyenMai);

                    } else {
                    }
                });
            } else {
            }

        });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>